spring:
  cloud:
    ai:
      tongyi:
        api-key: ${AI_API_KEY:sk-1e1895ea39be48a682fef3cfd948904d}
dubbo:
  application:
    name: spring-ai
    metadata-service-protocol: dubbo
  protocol:
    name: tri
    port: -1
  config-center:
    namespace: ${CONFIG_CENTER_NAMESPACE:68a980d3-b835-4ab1-904a-a952afee43b5}
    group: ${CONFIG_CENTER_GROUP:AI_GROUP}
    username: ${CONFIG_CENTER_USERNAME:nacos}
    password: ${CONFIG_CENTER_PASSWORD:12As4578}
    address: ${CONFIG_CENTER_ADDRESS:nacos://127.0.0.1:8848}