// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package org.stars.ai.service.proto;

public final class GreetProto {
  private GreetProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stars_ai_service_proto_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stars_ai_service_proto_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stars_ai_service_proto_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stars_ai_service_proto_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tapi.proto\022\032org.stars.ai.service.proto\"" +
      "?\n\014HelloRequest\022\017\n\007message\030\001 \001(\t\022\017\n\007grou" +
      "pId\030\002 \001(\t\022\r\n\005msgId\030\003 \001(\t\" \n\rHelloRespons" +
      "e\022\017\n\007message\030\001 \001(\t2\272\002\n\rTongYiService\022a\n\010" +
      "SayHello\022(.org.stars.ai.service.proto.He" +
      "lloRequest\032).org.stars.ai.service.proto." +
      "HelloResponse\"\000\022c\n\nGetPicture\022(.org.star" +
      "s.ai.service.proto.HelloRequest\032).org.st" +
      "ars.ai.service.proto.HelloResponse\"\000\022a\n\010" +
      "GetVoice\022(.org.stars.ai.service.proto.He" +
      "lloRequest\032).org.stars.ai.service.proto." +
      "HelloResponse\"\000BH\n\032org.stars.ai.service." +
      "protoB\nGreetProtoP\001Z\034dubbo-go-app/api/pr" +
      "oto;greetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_stars_ai_service_proto_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_stars_ai_service_proto_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stars_ai_service_proto_HelloRequest_descriptor,
        new String[] { "Message", "GroupId", "MsgId", });
    internal_static_org_stars_ai_service_proto_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_stars_ai_service_proto_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stars_ai_service_proto_HelloResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
