// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package org.stars.ai.service.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.stars.ai.service.proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string groupId = 2;</code>
   * @return The groupId.
   */
  String getGroupId();
  /**
   * <code>string groupId = 2;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string msgId = 3;</code>
   * @return The msgId.
   */
  String getMsgId();
  /**
   * <code>string msgId = 3;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();
}
